CREATE DATABASE IF NOT EXISTS PRACTICE;
USE PRACTICE;
CREATE TABLE P(
PRO_ID INT NOT NULL,
PRO_NAME VARCHAR(50),
PRICE INT NOT NULL
); 
INSERT INTO P
VALUES
(1,"SUGAR",50),
(2,"APPLE",100),
(3,"WHEAT",40),
(4,"CHOCLATE",45),
(5,"CAKES",55);

SELECT *
FROM P
WHERE PRICE BETWEEN 40 AND 60;

SELECT * 
FROM P
WHERE PRO_NAME LIKE "S%";

SELECT * FROM P
WHERE PRICE>0
LIMIT 3;