CREATE DATABASE ORB;
USE ORB;
CREATE TABLE ORB2(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
CITY VARCHAR(50)
);
INSERT INTO ORB2
value
(4,"MANSI",99,"LATUR"),
(5,"RAJ",94,"PUNE"),
(3,"ANJALI",92,"NASHIK"),
(1,"SANIKA",97,"PUNE"),
(2,"MANASVI",100,"LATUR");
SELECT * 
FROM ORB2
ORDER BY MARKS DESC
LIMIT 3;
SELECT SUM(MARKS) FROM ORB2;
SELECT MARKS,COUNT(NAME)
FROM ORB2
GROUP BY MARKS;
