CREATE DATABASE IF NOT EXISTS OP;
USE OP;
CREATE TABLE OP1(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
CITY VARCHAR(20)
);
INSERT INTO OP1
(ID ,NAME ,CITY)
VALUES
(101,"MANSI","LATUR"),
(102,"SANIKA","JALNA"),
(103,"RAJ","BARAMATI"),
(104,"MANASVI","LATUR");

SELECT* FROM OP1;

UPDATE OP1
SET ID=105
WHERE ID=103;

DELETE FROM OP1 WHERE ID=102;

TRUNCATE TABLE OP1;
