CREATE DATABASE IF NOT EXISTS COLLEGE4;
USE COLLEGE4;

CREATE TABLE DEP (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO DEP VALUES
(101, 'SCIENCE'),
(102, 'ENGLISH');

SELECT * FROM DEP;

SET SQL_SAFE_UPDATES=0;
UPDATE DEP
SET ID = 103
WHERE ID = 101;

CREATE TABLE TEACHER3(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEP_ID INT,
    FOREIGN KEY (DEP_ID) REFERENCES DEP(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

INSERT INTO TEACHER3 VALUES
(101, 'ALIA', 101),
(102, 'ARYA', 102);

 

