CREATE DATABASE IF NOT EXISTS DEPT;
USE DEPT;
CREATE TABLE SUB(
DID INT PRIMARY KEY,
NAME VARCHAR(50)
);
INSERT INTO SUB
VALUES
(101,"SCIENCE"),
(102,"MATH"),
(103,"ENGLISH");
SELECT * FROM SUB;

UPDATE SUB
SET DID=104
WHERE DID=102;

CREATE TABLE TEACH(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEP_ID INT,
FOREIGN KEY(DEP_ID) REFERENCES SUB(DID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
INSERT INTO TEACH 
VALUES
(101,"AMAN",102),
(102,"AARU",101);

SELECT*FROM TEACH;
