CREATE DATABASE IF NOT EXISTS FK;
USE FK;
CREATE TABLE FT(
DEP_ID INT PRIMARY KEY,
SUB VARCHAR(50)
);
INSERT INTO FT
(DEP_ID,SUB)
VALUES
(101,"SCIENCE"),
(102,"MATH");
SELECT * FROM FT;
SET SQL_SAFE_UPDATES=0;
UPDATE FT
SET DEP_ID=105
WHERE DEP_ID=101;

CREATE TABLE TT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SUB_ID INT ,
FOREIGN KEY(SUB_ID) REFERENCES FT(DEP_ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
INSERT INTO TT
VALUES
(101,"ASHA",101),
(103,"MONA",102),
(104,"ALIA",102),
(102,"AARU",101);
SELECT* FROM TT
ORDER BY ID ASC;