CREATE DATABASE SELF;
USE SELF;
CREATE TABLE SELF1(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
M_ID INT 
);
INSERT INTO SELF1
VALUES
(101,"AARU",102),
(102,"BIHU",104),
(103,"CRAZY",102),
(104,"DONALD",NULL);
SELECT * FROM SELF1;
SELECT *
FROM SELF1 AS a
JOIN SELF1 AS b
ON a.ID=b.M_ID;