CREATE DATABASE IF NOT EXISTS TAB;
USE TAB;
CREATE TABLE TA(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT DEFAULT 10000 ,
CITY VARCHAR(50)
);
INSERT INTO TA (ID, NAME, CITY, SALARY) VALUES
(101, 'MANSI', 'LATUR', 50000),
(102, 'ADITI', 'LATUR', 45000),
(103, 'POORTI', 'WAGHOLI', DEFAULT),  -- Use DEFAULT for default value
(104, 'NEHA', 'JALGAON', 10005),
(105, 'ASH', 'NAGPUR', DEFAULT);  -- Use DEFAULT for default value


SELECT * FROM TA;
SELECT COUNT(ID) FROM TA;
SELECT SUM(SALARY) FROM TA;

SELECT CITY,COUNT(SALARY)
FROM TA
GROUP BY CITY
HAVING SUM(SALARY)>1000;


