CREATE DATABASE IF NOT EXISTS ALT;
USE ALT;
CREATE TABLE ALT1(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEP VARCHAR(50)
);
INSERT INTO ALT1
VALUES 
(101,"MANSI","IT"),
(102,"ADITI","SOFT"),
(103,"NEHA","HR"),
(104,"PRANJAL","MANAGER");
SELECT * FROM ALT;

ALTER TABLE ALT1
RENAME TO ALT;

TRUNCATE TABLE ALT;
DROP TABLE ALT;
