CREATE DATABASE IF NOT EXISTS RECORDS;
USE RECORDS;
CREATE TABLE IF NOT EXISTS R(
NAME VARCHAR(50) NOT NULL,
MARKS INT NOT NULL,
GRADE VARCHAR(5)
);
INSERT INTO R
VALUES
("ASHA",89,"B"),
("PRATHA",56,"E"),
("ALIA",99,"A"),
("MADHU",95,"A"),
("SARU",78,"C"),
("KIYA",99,"A"),
("MEERA",90,"A");

SELECT * FROM R;


