CREATE DATABASE QUE;
USE QUE;
CREATE TABLE QUE1(
MARKS INT ,
CITY VARCHAR(50)
);
INSERT INTO QUE1
VALUES
(99,"LATUR"),
(98,"PUNE"),
(99,"MUMBAI"),
(94,"PUNE"),
(94,"LATUR");
SELECT CITY,AVG(MARKS)
FROM QUE1
GROUP BY CITY
ORDER BY AVG(MARKS);