SELECT TOP (1000) [EXAMNO]
      ,[SNAME]
      ,[PHY]
      ,[CHE]
      ,[BIO]
      ,[TOTAL]
      ,[RESULT]
      ,[GRADE]
      ,[PERC]
  FROM [master].[dbo].[NEET]

  SELECT  A.[EXAMNO]
      ,A.[SNAME]
	  ,B.[SCHOOL]
	  ,B.[DISTRICT]
      ,A.[PHY]
      ,A.[CHE]
      ,A.[BIO]
      ,A.[TOTAL]
      ,A.[RESULT]
      ,A.[GRADE]
      ,A.[PERC]
  FROM [master].[dbo].[NEET] A
  LEFT JOIN (SELECT * FROM  [master].[dbo].[NMASTER] ) B ON B.EXAMNO=A.EXAMNO WHERE A.EXAMNO='NT002'
