CREATE DATABASE DUP;
USE DUP;
CREATE TABLE DUP2(
NAME VARCHAR(50),
CITY VARCHAR(50),
GRADE VARCHAR(5)
);
INSERT INTO DUP2
VALUES
("A","LATUR","A"),
("B","JALNA","B"), 
("A","PUNE","A+"),
("D","LATUR","A"),
("E","BARAMATI","B+");
SELECT * FROM DUP2 WHERE GRADE='A+' ;
SELECT * FROM DUP2 WHERE CITY='LATUR';